// ... other lines of code ...

// Line 111 Update
const heroText = "A student-led projects program involving students from universities accross the United States, including Berkeley, Purdue, and UChicago.";

// ... other lines of code ...